### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by erdeerdeerde** [zgyarmati/aptly-plugin#2]
Hi,

Since you asked for it ...

I would like support for HTTPS in the plugin, so the credentials are not sent in plain text to the Aptly API.

Thanks,
Martin

**Comment by zgyarmati** [comment]
Fixed, but please note that also the site config has changed, which will slightly mess up your config.

**Comment by erdeerdeerde** [comment]
works like a charm, thanks!
