### ISSUE TITLE
Re-implement site config form login check

### ISSUE THREAD

**Issue by zgyarmati** [zgyarmati/aptly-plugin#4]
The site configuration form currently doesn't check the validity of the config upon entering, even the old partially working implementation is removed, so it's needs to be re-implemented.
(Or maybe even consider to add a specific "Connection test" button which would request the /api/version ?)

**Comment by erdeerdeerde** [comment]
+1 for a connection test button.

**Comment by erdeerdeerde** [comment]
I have tested the "Connection Test" button and it works fine, the only downside is that the error messages are not very helpful, they always state a "com.mashape.unirest.http.exceptions.UnirestException" and don´t give a hint at what is actually wrong eg. if the credentials are wrong or the plugin could not connect to the repo server.
