### ISSUE TITLE
add option to sign repository

### ISSUE THREAD

**Issue by erdeerdeerde** [zgyarmati/aptly-plugin#5]
Hi,

I would like to sign repositories, until now i had to change the sourcecode of the plugin manually to achive that.
I would like a checkbox in the global configuration that i can select to sign the repositories in a specific aptly site.

**Comment by zgyarmati** [comment]
First version is committed, but some additional testing would be extremely handy here, as i had difficulties with testing this with gpg2, and i couldn't make all of the setups work on the GPG side of things...

**Comment by erdeerdeerde** [comment]
Hi, I have tested with gnupg2 and it has worked fine.

**Comment by zgyarmati** [comment]
Great, thx, then i'll do some further refactoring, and start to submit it to plugins.jenkins.io
